### ISSUE TITLE
Cannot register token if token begins with '\x21\x10'

### ISSUE THREAD

**Issue by weeebdev** [ss23/fortitoken-mobile-registration#3]
Surprisingly, my token that works on the FortToken after b32decode begins with `\x21\x10` and is unable to register with the following error:
```json
{'error_code': 40, 'error_message': 'FTM token Activation Code is invalid'}
```

**Comment by randomstuff** [comment]
The `\x10` probably represents different TOTP parameters or maybe a different key "encryption" method. I messed around with the different parameters (mostly the hash method) without success for now.

**Comment by randomstuff** [comment]
According to [`denngie/fortitoken-decrypt`](https://github.com/denngie/fortitoken-decrypt/blob/main/decrypt.py) some token would use SHA1 but with a time step of 60s instead of 30s (which is the default and what is used in this script).

**Comment by Zasch** [comment]
Is there a way to set it to a time step of 60s?

**Comment by randomstuff** [comment]
Most HOTP/TOTP programs can used a custom time step parameter:

* For `oathtool`, this is `-s 60`.
* For [`otpauth` URIs](https://docs.yubico.com/yesdk/users-manual/application-oath/uri-string-format.html) (and QR codes), this is `...&period=60`.

Note that I do not know if this fixes the issue. Maybe this parameter does not apply based for this version and maybe other things have to be changed (such as the secret derivation mechanism, the hash algorithm, etc).

**Comment by ddoomenbsu** [comment]
> According to [`denngie/fortitoken-decrypt`](https://github.com/denngie/fortitoken-decrypt/blob/main/decrypt.py) some token would use SHA1 but with a time step of 60s instead of 30s (which is the default and what is used in this script).

Is there a way to test if this works (by altering the script to use 60s when 'begins with \x21\x10' is not true)?

**Comment by randomstuff** [comment]
After checking the error and the code, I'm not sure this issue is actually the same that I had so I don't believe my comments are relevant for this error.

**Comment by ss23** [comment]
If anyone is able to share information on how they got a token that is considered invalid (such that I can try get one myself), I am happy to take a look and try figure out what is going on. Without this, it is difficult to understand what is different about the different versions, but it's probably a simple change, just difficult to determine without seeing an example (or reversing the mobile application).

**Comment by weeebdev** [comment]
Apologies.
I completely forgot about this issue. Later in the day, I was able to retrieve the token and generate totp. I don't really remember which tool I used and how I did that tho.
You can close the issue if this became irrelevant

**Comment by randomstuff** [comment]
>  I was able to retrieve the token and generate totp.

Having more information about this would be quite interesting :)

**Comment by ddoomenbsu** [comment]
Problem for me was that the token was registered by a colleague of mine around the same time, but he was faster :)

**Comment by weeebdev** [comment]
> > I was able to retrieve the token and generate totp.
> 
> Having more information about this would be quite interesting :)

I wish I remembered. Just spent an hour trying to figure out how I managed to do that, but nothing came to mind. But the issue is repeatable with the following token: "EEIHVK54DDCWV55A" (this is the expired one, so I think it should be safe to share)



> Most HOTP/TOTP programs can used a custom time step parameter:
> 
> * For `oathtool`, this is `-s 60`.
> * For [`otpauth` URIs](https://docs.yubico.com/yesdk/users-manual/application-oath/uri-string-format.html) (and QR codes), this is `...&period=60`.
> 
> Note that I do not know if this fixes the issue. Maybe this parameter does not apply based for this version and maybe other things have to be changed (such as the secret derivation mechanism, the hash algorithm, etc).

This was exactly the case for me! Spent a lot of time with this.

**Comment by ss23** [comment]
> 
> > Most HOTP/TOTP programs can used a custom time step parameter:
> > 
> > * For `oathtool`, this is `-s 60`.
> > * For [`otpauth` URIs](https://docs.yubico.com/yesdk/users-manual/application-oath/uri-string-format.html) (and QR codes), this is `...&period=60`.
> > 
> > Note that I do not know if this fixes the issue. Maybe this parameter does not apply based for this version and maybe other things have to be changed (such as the secret derivation mechanism, the hash algorithm, etc).
> 
> This was exactly the case for me! Spent a lot of time with this.

Just to clarify @weeebdev, all you needed to do was change the token generation to `oathtool [token]` to `oathtool [token] -s 60` and it worked?

If so, then it seems like a simple fix - if the token prefix is `\x21\x00`, the timestep is 30 seconds, but if it's `\x21\x10`, the timestep is 60 seconds. This means if your token starts with "EEA", you've got a 30 second token, but "EEI" is a 60 second token.

Is anyone else able to confirm this behavior? If so, I'll make a change to the code for this. Unfortunately, I haven't seen a token like this myself to verify this myself.

**Comment by weeebdev** [comment]
> > > Most HOTP/TOTP programs can used a custom time step parameter:
> > > 
> > > * For `oathtool`, this is `-s 60`.
> > > * For [`otpauth` URIs](https://docs.yubico.com/yesdk/users-manual/application-oath/uri-string-format.html) (and QR codes), this is `...&period=60`.
> > > 
> > > Note that I do not know if this fixes the issue. Maybe this parameter does not apply based for this version and maybe other things have to be changed (such as the secret derivation mechanism, the hash algorithm, etc).
> > 
> > 
> > This was exactly the case for me! Spent a lot of time with this.
> 
> Just to clarify @weeebdev, all you needed to do was change the token generation to `oathtool [token]` to `oathtool [token] -s 60` and it worked?
> 
> If so, then it seems like a simple fix - if the token prefix is `\x21\x00`, the timestep is 30 seconds, but if it's `\x21\x10`, the timestep is 60 seconds. This means if your token starts with "EEA", you've got a 30 second token, but "EEI" is a 60 second token.
> 
> Is anyone else able to confirm this behavior? If so, I'll make a change to the code for this. Unfortunately, I haven't seen a token like this myself to verify this myself.

I wish I was able to recall something. I *don't remember*.
Let's just wait until somebody else will face that issue again or I'll get another token.

**Comment by mcmaxl** [comment]
Hi all, my token also begins with "EEI" - I get the error:

`Token did not begin with !
{'error_code': 40, 'error_message': 'FTM token Activation Code is invalid'}
Traceback (most recent call last):
  File "/Users/maxl/Downloads/fortitoken-mobile-registration-main/register-token.py", line 117, in <module>
    main(args)
    ~~~~^^^^^^
  File "/Users/maxl/Downloads/fortitoken-mobile-registration-main/register-token.py", line 95, in main
    totp = register_token(token, mobile_id)
  File "/Users/maxl/Downloads/fortitoken-mobile-registration-main/register-token.py", line 38, in register_token
    raise Exception("Could not register token")`

where can I change the timestep to 60s? I only found one reference to oathtool in the code in line 99:

`    print(f"To generate a token now, run: oathtool --totp {totp.hex()}")`

**Comment by mcmaxl** [comment]
ps: and as I can see in the FortiToken app: it is a 60 second token

**Comment by randomstuff** [comment]
@mcmaxl, If using oathtool, you change the timestep with `-s 60` as explained in my previous comment.

**Comment by mcmaxl** [comment]
> [@mcmaxl](https://github.com/mcmaxl), If using oathtool, you change the timestep with `-s 60` as explained in my previous comment.

I just don't get in which line i can change it as I can't find any reference to either oathtool or otpauth in the code - note that I am a total noob ;)

**Comment by ljrk0** [comment]
This is indeed the issue, from the decompiled FortiMobile app (with some renames):

```java
        } else if (rawToken.length() == 16) { // 10 Byte Base32 encoded
            Charset charset = C1737a.standardCharset;
            byte[] base32Decode = C1819h6.base32Decode(rawToken);
            this.version = decodeVersion(base32Decode);
            this.tokenType = decodeTokenType(base32Decode);
            byte b = base32Decode[1];
            this.digits = ((b >> 5) & 7) != 1 ? 6 : 8; // \x20 -> 8 digit code
            this.seconds = ((b >> 4) & 1) == 0 ? 30 : 60; // \x10 -> 60s
            StringBuilder sb = new StringBuilder(16);
            for (int i = 2; i < base32Decode.length; i++) {
                sb.append(String.format("%02X", Byte.valueOf(base32Decode[i])));
            }
            this.token_activation_code = sb.toString();
            Charset charset2 = C1737a.standardCharset;
            this.__unused = 1;
        } else {
```

We can deduce that if the lowest bit in the upper nibble is set, we need to use `-s 60` and if the second-lowest bit is set, `-d 8` for oathtool.

Further, the functions `decodeVersion` and `decodeTokenType` look as such:

```java
    public static int decodeVersion(byte[] rawToken) {
        return (rawToken[0] >> 3) & 31;
    }

    // [...]

    public static TokenType decodeTokenType(byte[] rawToken) {
        int tokenType = rawToken[0] & 7;
        Object obj = C2728sh.f4647a;
        Charset charset = C1737a.standardCharset;
        TokenType totpTokenType = TokenType.TIME_BASED_TOKEN;
        if (tokenType == totpTokenType.id) {
            return tokenType;
        }
        TokenType hotpTokenType = TokenType.COUNTER_BASED_TOKEN;
        return tokenType == hotpTokenType.id ? hotpTokenType : totpTokenType;
    }
```

Namely, the upmost 5 bits of the first byte encode the version `\x21 >> 3 = \x04`, the remaining lower three bits encode the type, with 1 meaning "TOTP" and 0 meaning "HOTP", as can be seen from the following enum:

```java
public enum TokenType {
    COUNTER_BASED_TOKEN("hotp", 0),
    TIME_BASED_TOKEN("totp", 1);
    // [...]
}

So, if the first byte is uneven, e.g. `\x20`, then the `--hotp` flag for oathtool should be used instead of `--totp`.

**Comment by weeebdev** [comment]
I managed to get it again:
```sh
λ python3 register-token.py EEIJ##### --mobile-id 200f#######
Token did not begin with !
Token registered: 71b2####### (base32: OGZ#######)
To generate a token now, run: oathtool --totp 71b2#####
```
again, step 60s did help

**Comment by weeebdev** [comment]
> > > Most HOTP/TOTP programs can used a custom time step parameter:
> > > 
> > > * For `oathtool`, this is `-s 60`.
> > > * For [`otpauth` URIs](https://docs.yubico.com/yesdk/users-manual/application-oath/uri-string-format.html) (and QR codes), this is `...&period=60`.
> > > 
> > > Note that I do not know if this fixes the issue. Maybe this parameter does not apply based for this version and maybe other things have to be changed (such as the secret derivation mechanism, the hash algorithm, etc).
> > 
> > 
> > This was exactly the case for me! Spent a lot of time with this.
> 
> Just to clarify [@weeebdev](https://github.com/weeebdev), all you needed to do was change the token generation to `oathtool [token]` to `oathtool [token] -s 60` and it worked?
> 
> If so, then it seems like a simple fix - if the token prefix is `\x21\x00`, the timestep is 30 seconds, but if it's `\x21\x10`, the timestep is 60 seconds. This means if your token starts with "EEA", you've got a 30 second token, but "EEI" is a 60 second token.
> 
> Is anyone else able to confirm this behavior? If so, I'll make a change to the code for this. Unfortunately, I haven't seen a token like this myself to verify this myself.

can confirm again
